flectra.define('test_website_slides_full.tour.slide.certification.member',function(require){
"usestrict";

vartour=require('web_tour.tour');

/**
 *Thepurposeofthistouristocheckthewholecertificationflow:
 *
 *->student(=demouser)checks'onpayment'coursecontent
 *->clickson"buycourse"
 *->isredirectedtowebshopontheproductpage
 *->buysthecourse
 *->fails3times,exhaustinghisattempts
 *->isremovedtothemembersofthecourse
 *->buysthecourseagain
 *->succeedsthecertification
 *->hasthecoursemarkedascompleted
 *->hasthecertificationinhisuserprofile
 *
 */

varinitTourSteps=[{
    content:'eLearning:gotocertificationcourse',
    trigger:'a:contains("DIYFurniture-TEST")'
},{
    content:'eLearning:doesnothaveaccesstocertification',
    trigger:'.o_wslides_course_main',
    run:function(){
        //checkthatuserdoesn'thaveaccesstocoursecontent
        if($('.o_wslides_slides_list_slide.o_wslides_js_slides_list_slide_link').length===0){
            $('.o_wslides_course_main').addClass('empty-content-success');
        }
    }
},{
    content:'eLearning:previousstepcheck',
    trigger:'.o_wslides_course_main.empty-content-success',
    run:function(){}//checkthatpreviousstepsucceeded
}];

varbuyCertificationSteps=[{
    content:'eLearning:trytobuycourse',
    trigger:'a:contains("AddtoCart")'
},{
    content:'eCommerce:ProcessCheckout',
    trigger:'a:contains("ProcessCheckout")'
},{
    content:'eCommerce:selectTestpaymentacquirer',
    trigger:'.o_payment_acquirer_select:contains("Test")'
},{
    content:'eCommerce:addcardnumber',
    trigger:'input[name="cc_number"]',
    run:'text4242424242424242'
},{
    content:'eCommerce:addcardholdername',
    trigger:'input[name="cc_holder_name"]',
    run:'textMarcDemo'
},{
    content:'eCommerce:addcardexpirydate',
    trigger:'input[name="cc_expiry"]',
    run:'text11/50'
},{
    content:'eCommerce:addcardcvc',
    trigger:'input[name="cvc"]',
    run:'text999'
},{
    content:'eCommerce:pay',
    trigger:'#o_payment_form_pay'
},{
    content:'eCommerce:checkthatthepaymentissuccessful',
    trigger:'.oe_website_sale_tx_status:contains("Yourpaymenthasbeensuccessfullyprocessed")',
    run:function(){}
},{
    content:'eCommerce:gobacktoe-learninghomepage',
    trigger:'.nav-link:contains("Courses")'
},{
    content:'eLearning:gointoboughtcourse',
    trigger:'a:contains("DIYFurniture")'
},{
    content:'eLearning:usershouldbeenrolled',
    trigger:'.o_wslides_js_course_join:contains("You\'reenrolled")',
    run:function(){}
},{
    content:'eLearning:startcourse',
    trigger:'.o_wslides_js_slides_list_slide_link'
}];

varfailCertificationSteps=[{
    content:'eLearning:startcertification',
    trigger:'button:contains("StartCertification")'
},{//Question:Whattypeofwoodisthebestforfurniture?
    content:'Survey:selectinganswer"Fir"',
    trigger:'div.js_question-wrapper:contains("Whattypeofwoodisthebestforfurniture")label:contains("Fir")'
},{//Question:Selectallthefurnitureshowninthevideo
    content:'Survey:tickinganswer"Table"',
    trigger:'div.js_question-wrapper:contains("Selectallthefurnitureshowninthevideo")label:contains("Table")'
},{
    content:'Survey:tickinganswer"Bed"',
    trigger:'div.js_question-wrapper:contains("Selectallthefurnitureshowninthevideo")label:contains("Bed")'
},{
    content:'Survey:submittingthecertificationwithwronganswers',
    trigger:'button:contains("Submit")'
}];

varretrySteps=[{
    content:'Survey:retrycertification',
    trigger:'a:contains("Retry")'
}];

varsucceedCertificationSteps=[{
    content:'eLearning:startcertification',
    trigger:'button:contains("StartCertification")'
},{//Question:Whattypeofwoodisthebestforfurniture?
    content:'Survey:selectinganswer"Oak"',
    trigger:'div.js_question-wrapper:contains("Whattypeofwoodisthebestforfurniture")label:contains("Oak")',
},{//Question:Selectallthefurnitureshowninthevideo
    content:'Survey:tickinganswer"Chair"',
    trigger:'div.js_question-wrapper:contains("Selectallthefurnitureshowninthevideo")label:contains("Chair")'
},{
    content:'Survey:tickinganswer"Shelve"',
    trigger:'div.js_question-wrapper:contains("Selectallthefurnitureshowninthevideo")label:contains("Shelve")'
},{
    content:'Survey:tickinganswer"Desk"',
    trigger:'div.js_question-wrapper:contains("Selectallthefurnitureshowninthevideo")label:contains("Desk")'
},{
    content:'Survey:submittingthecertificationwithcorrectanswers',
    trigger:'button:contains("Submit")'
}];

varcertificationCompletionSteps=[{
    content:'Survey:checkcertificationsuccessful',
    trigger:'div:contains("Congratulations,youhavepassedthetest")',
    run:function(){}
},{
    content:'Survey:backtocoursehomepage',
    trigger:'a:contains("Gobacktocourse")'
},{
    content:'eLearning:backtoe-learninghomepage',
    trigger:'.nav-link:contains("Courses")'
},{
    content:'eLearning:courseshouldbecompleted',
    trigger:'.o_wslides_course_card:contains("DIYFurniture").badge-pill:contains("Completed")',
    run:function(){}
}];

varprofileSteps=[{
    content:'eLearning:accessuserprofile',
    trigger:'.o_wslides_home_aside_loggedina:contains("View")'
},{
    content:'eLearning:checkthattheuserprofilecertificationsincludethenewcertification',
    trigger:'.o_wprofile_slides_course_card_body:contains("FurnitureCreationCertification")',
    run:function(){}
}];

tour.register('certification_member',{
    url:'/slides',
    test:true
},[].concat(
        initTourSteps,
        buyCertificationSteps,
        failCertificationSteps,
        retrySteps,
        failCertificationSteps,
        retrySteps,
        failCertificationSteps,
        [{trigger:'a:contains("Gobacktocourse")'}],
        buyCertificationSteps,
        succeedCertificationSteps,
        certificationCompletionSteps,
        profileSteps
    )
);

});
