#PartofFlectra.SeeLICENSEfileforfullcopyrightandlicensingdetails.

importflectra.tests

fromflectra.addons.base.tests.commonimportHttpCaseWithUserDemo


@flectra.tests.common.tagged('post_install','-at_install')
classTestUiCertification(HttpCaseWithUserDemo):

    defsetUp(self):
        super(TestUiCertification,self).setUp()

        self.survey_certification=self.env['survey.survey'].create({
            'title':'MyCompanyVendorCertification',
            'access_token':'4ead4bc8-b8f2-4760-a682-1fde8daaaaac',
            'state':'open',
            'access_mode':'public',
            'users_can_go_back':True,
            'users_login_required':True,
            'scoring_type':'scoring_with_answers',
            'certification':True,
            'certification_mail_template_id':self.env.ref('survey.mail_template_certification').id,
            'is_time_limited':'limited',
            'time_limit':10.0,
            'is_attempts_limited':True,
            'attempts_limit':2,
            'description':"""&lt;p&gt;Testyourvendorskills!.&lt;/p&gt;""",
            'question_and_page_ids':[
                (0,0,{
                    'title':'Products',
                    'sequence':1,
                    'is_page':True,
                    'question_type':False,
                    'description':'&lt;p&gt;Testyourknowledgeofyourproducts!&lt;/p&gt;',
                }),(0,0,{
                    'title':'DowesellAcousticBlocScreens?',
                    'sequence':2,
                    'question_type':'simple_choice',
                    'constr_mandatory':True,
                    'suggested_answer_ids':[
                        (0,0,{
                            'value':'No',
                            'sequence':1,
                        }),(0,0,{
                            'value':'Yes',
                            'sequence':2,
                            'is_correct':True,
                            'answer_score':2,
                        })
                    ],
                }),(0,0,{
                    'title':'Selectalltheexistingproducts',
                    'sequence':3,
                    'question_type':'multiple_choice',
                    'column_nb':'4',
                    'suggested_answer_ids':[
                        (0,0,{
                            'value':'Chairfloorprotection',
                            'sequence':1,
                            'is_correct':True,
                            'answer_score':1,
                        }),(0,0,{
                            'value':'Fanta',
                            'sequence':2,
                            'answer_score':-1,
                        }),(0,0,{
                            'value':'Conferencechair',
                            'sequence':3,
                            'is_correct':True,
                            'answer_score':1,
                        }),(0,0,{
                            'value':'Drawer',
                            'sequence':4,
                            'is_correct':True,
                            'answer_score':1,
                        }),(0,0,{
                            'value':'CustomizableLamp',
                            'sequence':5,
                            'answer_score':-1,
                        })
                    ]
                }),(0,0,{
                    'title':'SelectalltheavailablecustomizationsforourCustomizableDesk',
                    'sequence':4,
                    'question_type':'multiple_choice',
                    'column_nb':'4',
                    'suggested_answer_ids':[
                        (0,0,{
                            'value':'Color',
                            'sequence':1,
                            'is_correct':True,
                            'answer_score':1,
                        }),(0,0,{
                            'value':'Height',
                            'sequence':2,
                            'answer_score':-1,
                        }),(0,0,{
                            'value':'Width',
                            'sequence':3,
                            'is_correct':True,
                            'answer_score':1,
                        }),(0,0,{
                            'value':'Legs',
                            'sequence':4,
                            'is_correct':True,
                            'answer_score':1,
                        }),(0,0,{
                            'value':'Numberofdrawers',
                            'sequence':5,
                            'answer_score':-1,
                        })
                    ]
                }),(0,0,{
                    'title':'HowmanyversionsoftheCornerDeskdowehave?',
                    'sequence':5,
                    'question_type':'simple_choice',
                    'constr_mandatory':True,
                    'suggested_answer_ids':[
                        (0,0,{
                            'value':1,
                            'sequence':1,
                        }),(0,0,{
                            'value':2,
                            'sequence':2,
                            'is_correct':True,
                            'answer_score':2,
                        }),(0,0,{
                            'value':3,
                            'sequence':3,
                        }),(0,0,{
                            'value':4,
                            'sequence':4,
                        })
                    ]
                }),(0,0,{
                    'title':'Doyouthinkwehavemissingproductsinourcatalog?(notrated)',
                    'sequence':6,
                    'question_type':'text_box',
                }),(0,0,{
                    'title':'Prices',
                    'sequence':7,
                    'is_page':True,
                    'question_type':False,
                    'description':"""&lt;p&gt;Testyourknowledgeofourprices.&lt;/p&gt;""",
                }),(0,0,{
                    'title':'HowmuchdowesellourCableManagementBox?',
                    'sequence':8,
                    'question_type':'simple_choice',
                    'constr_mandatory':True,
                    'suggested_answer_ids':[
                        (0,0,{
                            'value':'$20',
                            'sequence':1,
                        }),(0,0,{
                            'value':'$50',
                            'sequence':2,
                        }),(0,0,{
                            'value':'$80',
                            'sequence':3,
                        }),(0,0,{
                            'value':'$100',
                            'sequence':4,
                            'is_correct':True,
                            'answer_score':2,
                        }),(0,0,{
                            'value':'$200',
                            'sequence':5,
                        }),(0,0,{
                            'value':'$300',
                            'sequence':6,
                        })
                    ]
                }),(0,0,{
                    'title':'Selectalltheproductsthatsellfor$100ormore',
                    'sequence':9,
                    'question_type':'multiple_choice',
                    'column_nb':'2',
                    'suggested_answer_ids':[
                        (0,0,{
                            'value':'CornerDeskRightSit',
                            'sequence':1,
                            'answer_score':1,
                            'is_correct':True,
                        }),(0,0,{
                            'value':'DeskCombination',
                            'sequence':2,
                            'answer_score':1,
                            'is_correct':True,
                        }),(0,0,{
                            'value':'CabinetwithDoors',
                            'sequence':3,
                            'answer_score':-1,
                        }),(0,0,{
                            'value':'LargeDesk',
                            'sequence':4,
                            'answer_score':1,
                            'is_correct':True,
                        }),(0,0,{
                            'value':'LetterTray',
                            'sequence':5,
                            'answer_score':-1,
                        }),(0,0,{
                            'value':'OfficeChairBlack',
                            'sequence':6,
                            'answer_score':-1,
                        }),
                    ]
                }),(0,0,{
                    'title':'Whatdoyouthinkaboutourprices(notrated)?',
                    'sequence':10,
                    'question_type':'simple_choice',
                    'constr_mandatory':True,
                    'suggested_answer_ids':[
                        (0,0,{
                            'value':'Veryunderpriced',
                            'sequence':1,
                        }),(0,0,{
                            'value':'Underpriced',
                            'sequence':2,
                        }),(0,0,{
                            'value':'Correctlypriced',
                            'sequence':3,
                        }),(0,0,{
                            'value':'Alittlebitoverpriced',
                            'sequence':4,
                        }),(0,0,{
                            'value':'Alotoverpriced',
                            'sequence':5,
                        })
                    ]
                }),(0,0,{
                    'title':'Policies',
                    'sequence':11,
                    'is_page':True,
                    'question_type':False,
                    'description':"""&lt;p&gt;Testyourknowledgeofourpolicies.&lt;/p&gt;""",
                }),(0,0,{
                    'title':'Howmanydaysisourmoney-backguarantee?',
                    'sequence':12,
                    'question_type':'numerical_box',
                    'constr_mandatory':True,
                    'is_scored_question':True,
                    'answer_numerical_box':30,
                    'answer_score':1,
                }),(0,0,{
                    'title':'Ifacustomerpurchasesaproducton6January2020,whatisthelatestdayweexpecttoshipit?',
                    'sequence':13,
                    'question_type':'date',
                    'is_scored_question':True,
                    'answer_date':'2020-01-08',
                    'answer_score':1,
                }),(0,0,{
                    'title':'Ifacustomerpurchasesa1yearwarrantyon6January2020,whendoweexpectthewarrantytoexpire?',
                    'sequence':14,
                    'question_type':'datetime',
                    'is_scored_question':True,
                    'answer_datetime':'2021-01-0700:00:01',
                    'answer_score':1,
                }),(0,0,{
                    'title':'Whatdaytoyouthinkisbestforustostarthavinganannualsale(notrated)?',
                    'sequence':15,
                    'question_type':'date',
                }),(0,0,{
                    'title':'Whatdayandtimedoyouthinkmostcustomersaremostlikelytocallcustomerservice(notrated)?',
                    'sequence':16,
                    'question_type':'datetime',
                }),(0,0,{
                    'title':'Howmanychairsdoyouthinkweshouldaimtosellinayear(notrated)?',
                    'sequence':17,
                    'question_type':'numerical_box',
                })
            ]
        })

    deftest_04_certification_success_tour(self):
        access_token=self.survey_certification.access_token
        self.start_tour("/survey/start/%s"%access_token,'test_certification_success',login="demo")

    deftest_05_certification_failure_tour(self):
        access_token=self.survey_certification.access_token
        self.start_tour("/survey/start/%s"%access_token,'test_certification_failure',login="demo")
