#PartofFlectra.SeeLICENSEfileforfullcopyrightandlicensingdetails.

importflectra.tests

fromflectra.addons.base.tests.commonimportHttpCaseWithUserDemo


@flectra.tests.common.tagged('post_install','-at_install')
classTestUiFeedback(HttpCaseWithUserDemo):

    defsetUp(self):
        super(TestUiFeedback,self).setUp()
        self.survey_feedback=self.env['survey.survey'].create({
            'title':'UserFeedbackForm',
            'access_token':'b137640d-14d4-4748-9ef6-344caaaaaae',
            'state':'open',
            'access_mode':'public',
            'users_can_go_back':True,
            'questions_layout':'page_per_section',
            'description':"""<p>ThissurveyallowsyoutogiveafeedbackaboutyourexperiencewithoureCommercesolution.
    Fillingithelpsusimprovingyourexperience.</p></field>""",
            'question_and_page_ids':[
                (0,0,{
                    'title':'Generalinformation',
                    'sequence':1,
                    'question_type':False,
                    'is_page':True,
                    'description':"""<p>Thissectionisaboutgeneralinformationaboutyou.Answeringthemhelpsqualifyingyouranswers.</p>""",
                }),(0,0,{
                    'title':'Wheredoyoulive?',
                    'sequence':2,
                    'question_type':'char_box',
                    'constr_mandatory':False,
                }),(0,0,{
                    'title':'Whenisyourdateofbirth?',
                    'sequence':3,
                    'question_type':'date',
                    'description':False,
                }),(0,0,{
                    'title':'Howfrequentlydoyoubuyproductsonline?',
                    'sequence':4,
                    'question_type':'simple_choice',
                    'comments_allowed':True,
                    'comment_count_as_answer':True,
                    'constr_mandatory':True,
                    'suggested_answer_ids':[
                        (0,0,{
                            'value':'Onceaday',
                            'sequence':1,
                        }),(0,0,{
                            'value':'Onceaweek',
                            'sequence':2,
                        }),(0,0,{
                            'value':'Onceamonth',
                            'sequence':3,
                        }),(0,0,{
                            'value':'Onceayear',
                            'sequence':4,
                        }),(0,0,{
                            'value':'Other(answerincomment)',
                            'sequence':5,
                        })],
                }),(0,0,{
                    'title':'Howmanytimesdidyouorderproductsonourwebsite?',
                    'sequence':5,
                    'question_type':'numerical_box',
                    'constr_mandatory':True,
                }),(0,0,{
                    'title':'Aboutourecommerce',
                    'sequence':6,
                    'is_page':True,
                    'question_type':False,
                    'description':"""<p>ThissectionisaboutoureCommerceexperienceitself.</p>""",
                }),(0,0,{
                    'title':'Whichofthefollowingwordswouldyouusetodescribeourproducts?',
                    'sequence':7,
                    'question_type':'multiple_choice',
                    'constr_mandatory':True,
                    'comments_allowed':True,
                    'comment_count_as_answer':False,
                    'suggested_answer_ids':[
                        (0,0,{
                            'value':'Highquality',
                            'sequence':1,
                        }),(0,0,{
                            'value':'Useful',
                            'sequence':2,
                        }),(0,0,{
                            'value':'Unique',
                            'sequence':3,
                        }),(0,0,{
                            'value':'Goodvalueformoney',
                            'sequence':4,
                        }),(0,0,{
                            'value':'Overpriced',
                            'sequence':5,
                        }),(0,0,{
                            'value':'Impractical',
                            'sequence':6,
                        }),(0,0,{
                            'value':'Ineffective',
                            'sequence':7,
                        }),(0,0,{
                            'value':'Poorquality',
                            'sequence':8,
                        }),(0,0,{
                            'value':'Other',
                            'sequence':9,
                        })],
                }),(0,0,{
                    'title':'WhatdoyourthinkaboutourneweCommerce?',
                    'sequence':8,
                    'question_type':'matrix',
                    'matrix_subtype':'multiple',
                    'constr_mandatory':True,
                    'suggested_answer_ids':[(0,0,{
                        'value':'Totallydisagree',
                        'sequence':1
                    }),(0,0,{
                        'value':'Disagree',
                        'sequence':2,
                    }),(0,0,{
                        'value':'Agree',
                        'sequence':3,
                    }),(0,0,{
                        'value':'Totallyagree',
                        'sequence':4,
                    })],
                    'matrix_row_ids':[(0,0,{
                        'value':'Thenewlayoutanddesignisfreshandup-to-date',
                        'sequence':1,
                    }),(0,0,{
                        'value':'ItiseasytofindtheproductthatIwant',
                        'sequence':2,
                    }),(0,0,{
                        'value':'Thetooltocomparetheproductsisusefultomakeachoice',
                        'sequence':3,
                    }),(0,0,{
                        'value':'Thecheckoutprocessisclearandsecure',
                        'sequence':4,
                    }),(0,0,{
                        'value':'Ihaveaddedproductstomywishlist',
                        'sequence':5,
                    })],
                }),(0,0,{
                    'title':'Doyouhaveanyothercomments,questions,orconcerns?',
                    'sequence':9,
                    'question_type':'text_box',
                    'constr_mandatory':False,
                })
            ],
        })


    deftest_01_admin_survey_tour(self):
        access_token=self.survey_feedback.access_token
        self.start_tour("/survey/start/%s"%access_token,'test_survey',login="admin")

    deftest_02_demo_survey_tour(self):
        access_token=self.survey_feedback.access_token
        self.start_tour("/survey/start/%s"%access_token,'test_survey',login="demo")

    deftest_03_public_survey_tour(self):
        access_token=self.survey_feedback.access_token
        self.start_tour("/survey/start/%s"%access_token,'test_survey')

    deftest_04_public_survey_with_triggers(self):
        """Checkthatchainedconditionalquestionsarecorrectly
        hiddenfromsurveywhenapreviouslyselectedtriggeringansweris
        unselected.E.g.,ifaspecificanswerfor"Question1"isselected,
        whichtriggersasking"Question2",andaspecificanswerfor
        "Question2"isselectedandtriggersasking"Question3",
        changingtheselectedanswerfor"Question1"should:
          *hidequestions2and3
          *enablesubmittingthesurveywithoutansweringquestions2and3,
           evenif"constr_mandatory=True",astheyarenotvisible.
        """
        survey_with_triggers=self.env['survey.survey'].create({
            'title':'SurveyWithTriggers',
            'access_token':'3cfadce3-3f7e-41da-920d-10fa0eb19527',
            'state':'open',
            'access_mode':'public',
            'users_can_go_back':True,
            'questions_layout':'one_page',
            'description':"<p>Testsurveywithconditionalquestions</p>",
            'question_and_page_ids':[
                (0,0,{
                    'title':'Q1',
                    'sequence':1,
                    'question_type':'simple_choice',
                    'suggested_answer_ids':[
                        (0,0,{
                            'value':'Answer1',
                            'sequence':1,
                        }),(0,0,{
                            'value':'Answer2',
                            'sequence':2,
                        }),
                    ],
                    'constr_mandatory':True,
                }),(0,0,{
                    'title':'Q2',
                    'sequence':2,
                    'question_type':'simple_choice',
                    'suggested_answer_ids':[
                        (0,0,{
                            'value':'Answer1',
                            'sequence':1,
                        }),(0,0,{
                            'value':'Answer2',
                            'sequence':2,
                        })
                    ],
                    'is_conditional':True,
                    'constr_mandatory':True,
                }),(0,0,{
                    'title':'Q3',
                    'sequence':3,
                    'question_type':'simple_choice',
                    'suggested_answer_ids':[
                        (0,0,{
                            'value':'Answer1',
                            'sequence':1,
                        }),(0,0,{
                            'value':'Answer2',
                            'sequence':2,
                        })
                    ],
                    'is_conditional':True,
                    'constr_mandatory':True,
                }),
            ]
        })

        q1=survey_with_triggers.question_ids.filtered(lambdaq:q.title=='Q1')
        q1_a1=q1.suggested_answer_ids.filtered(lambdaa:a.value=='Answer1')
        q2=survey_with_triggers.question_ids.filtered(lambdaq:q.title=='Q2')
        q2_a1=q2.suggested_answer_ids.filtered(lambdaa:a.value=='Answer1')
        q3=survey_with_triggers.question_ids.filtered(lambdaq:q.title=='Q3')

        q2.triggering_question_id=q1
        q2.triggering_answer_id=q1_a1

        q3.triggering_question_id=q2
        q3.triggering_answer_id=q2_a1

        access_token=survey_with_triggers.access_token
        self.start_tour("/survey/start/%s"%access_token,'test_survey_chained_conditional_questions')

    deftest_06_survey_prefill(self):
        access_token=self.survey_feedback.access_token
        self.start_tour("/survey/start/%s"%access_token,'test_survey_prefill')
