stages:
  - unittest
  - build
  - integrationtest

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CI_PROJECT_NAMESPACE: jamotion

  # Configure postgres service (https://hub.docker.com/_/postgres/)
  POSTGRES_DB: postgres
  POSTGRES_USER: flectra
  POSTGRES_PASSWORD: flectra
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"

before_script:
# - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

job_jamo_test:
  image: registry.gitlab.com/${CI_PROJECT_NAMESPACE}/flectra/ubuntu_base:latest
  stage: unittest
  script:
    - su - flectra -c "locale"

#job_test_base_9:
#  image: registry.gitlab.com/${CI_PROJECT_NAMESPACE}/flectra/ubuntu_base:latest
#  services:
#    - postgres:9
#  stage: unittest
#  script:
#    - su - flectra -c "locale"
#    - su - flectra -c "cd ${CI_PROJECT_DIR} && ./setup/docker/gitlab-ci/gitlab_test_flectra.py --build=base"
#
#job_test_all_9:
#  image: registry.gitlab.com/${CI_PROJECT_NAMESPACE}/flectra/ubuntu_base:latest
#  services:
#    - postgres:9
#  stage: unittest
#  script:
#    - echo -e 'LANG="en_US.UTF-8"\nLANGUAGE="en_US:en"\n' > /etc/default/locale
#    - su - flectra -c "cd ${CI_PROJECT_DIR} && ./setup/docker/gitlab-ci/gitlab_test_flectra.py --build=all"
#
#job_test_base_10:
#  image: registry.gitlab.com/${CI_PROJECT_NAMESPACE}/flectra/ubuntu_base:latest
#  services:
#    - postgres:10
#  stage: unittest
#  script:
#    - echo -e 'LANG="en_US.UTF-8"\nLANGUAGE="en_US:en"\n' > /etc/default/locale
#    - su - flectra -c "cd ${CI_PROJECT_DIR} && ./setup/docker/gitlab-ci/gitlab_test_flectra.py --build=base"
#
#job_test_all_10:
#  image: registry.gitlab.com/${CI_PROJECT_NAMESPACE}/flectra/ubuntu_base:latest
#  services:
#    - postgres:10
#  stage: unittest
#  script:
#    - echo -e 'LANG="en_US.UTF-8"\nLANGUAGE="en_US:en"\n' > /etc/default/locale
#    - su - flectra -c "cd ${CI_PROJECT_DIR} && ./setup/docker/gitlab-ci/gitlab_test_flectra.py --build=all"
#
#build:base:ubuntu:
#  only:
#    - schedules
#  image: docker:stable
#  services:
#    - docker:dind
#  script:
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
#    - docker build -f ./setup/docker/ubuntu_base/Dockerfile ./setup/docker/
#
#build:base:debian:
#  only:
#    - schedules
#  image: docker:stable
#  services:
#    - docker:dind
#  script:
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
#    - docker build -f ./setup/docker/debian_base/Dockerfile ./setup/docker/
#
#build:flectra:ubuntu:
#  stage: build
#  image: docker:stable
#  services:
#    - docker:dind
#  script:
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
#    - docker build -f ./setup/docker/ubuntu_flectra/Dockerfile ./setup/docker/
#
#build:flectra:debian:
#  stage: build
#  image: docker:stable
#  services:
#    - docker:dind
#  script:
#    - docker build -f ./setup/docker/debian_flectra/Dockerfile ./setup/docker/
#
#
#job_integrationtest_ubuntu_base_9:
#  image: registry.gitlab.com/${CI_PROJECT_NAMESPACE}/flectra/ubuntu_flectra:latest
#  services:
#    - postgres:9
#  stage: integrationtest
#  script:
#    - cd ${CI_PROJECT_DIR} && ./setup/docker/gitlab-ci/gitlab_test_flectra.py --build=base --server-path=/opt/flectra/flectra
#
#job_integrationtest_ubuntu_all_9:
#  image: registry.gitlab.com/${CI_PROJECT_NAMESPACE}/flectra/ubuntu_flectra:latest
#  services:
#    - postgres:9
#  stage: integrationtest
#  script:
#    - cd ${CI_PROJECT_DIR} && ./setup/docker/gitlab-ci/gitlab_test_flectra.py --build=all --server-path=/opt/flectra/flectra
#
#job_integrationtest_debian_base_9:
#  image: registry.gitlab.com/${CI_PROJECT_NAMESPACE}/flectra/debian_flectra:latest
#  services:
#    - postgres:9
#  stage: integrationtest
#  script:
#    - cd ${CI_PROJECT_DIR} && ./setup/docker/gitlab-ci/gitlab_test_flectra.py --build=base --server-path=/opt/flectra/flectra
#
#job_integrationtest_debian_all_9:
#  image: registry.gitlab.com/${CI_PROJECT_NAMESPACE}/flectra/debian_flectra:latest
#  services:
#    - postgres:9
#  stage: integrationtest
#  script:
#    - cd ${CI_PROJECT_DIR} && ./setup/docker/gitlab-ci/gitlab_test_flectra.py --build=all --server-path=/opt/flectra/flectra
