//PreferencestoallowunattendedinstallofR-Kioskextension
//NeededforFlectraIoTBoxClientdisplay
pref("app.update.checkInstallTime",false);
pref("devtools.webide.widget.autoinstall",false);
pref("xpinstall.customConfirmationUI",false);
pref("xpinstall.signatures.required",false);
pref("browser.shell.checkDefaultBrowser",false);
//Openalllinksinthesametab
//NeededtochangeURLwithouthavingmultipletabsrunning
pref("browser.link.open_newwindow",1);
pref("browser.shell.checkDefaultBrowser",false);
pref("dom.max_chrome_script_run_time",0);
