#!/usr/bin/envpython2
#PartofFlectra.SeeLICENSEfileforfullcopyrightandlicensingdetails.
#
#flectra-mailgate
#
#Thisprogramwillreadanemailfromstdinandforwardittoflectra.Configure
#apipealiasinyourmailservertouseit,postfixusesasyntaxthatlooks
#like:
#
#email@address:"|/home/flectra/src/flectra-mail.py"
#
#whileeximusesasyntaxthatlookslike:
#
#*:|/home/flectra/src/flectra-mail.py
#
#Notepython2waschosenonpurposeforbackwardcompatibilitywitholdmail
#servers.
#
importoptparse
importsys
importtraceback
importxmlrpclib

defmain():
    op=optparse.OptionParser(usage='usage:%prog[options]',version='%progv1.2')
    op.add_option("-d","--database",dest="database",help="Flectradatabasename(default:%default)",default='flectra')
    op.add_option("-u","--userid",dest="userid",help="Flectrauseridtoconnectwith(default:%default)",default=1,type=int)
    op.add_option("-p","--password",dest="password",help="Flectrauserpassword(default:%default)",default='admin')
    op.add_option("--host",dest="host",help="Flectrahost(default:%default)",default='localhost')
    op.add_option("--port",dest="port",help="Flectraport(default:%default)",default=7073,type=int)
    (o,args)=op.parse_args()

    try:
        msg=sys.stdin.read()
        models=xmlrpclib.ServerProxy('http://%s:%s/xmlrpc/2/object'%(o.host,o.port),allow_none=True)
        models.execute_kw(o.database,o.userid,o.password,'mail.thread','message_process',[False,xmlrpclib.Binary(msg)],{})
    exceptxmlrpclib.Faultase:
        #reformatxmlrpcfaultstoprintareadabletraceback
        err="xmlrpclib.Fault:%s\n%s"%(e.faultCode,e.faultString)
        sys.exit(err)
    exceptExceptionase:
        traceback.print_exc(None,sys.stderr)
        sys.exit(2)

if__name__=='__main__':
    main()
