#-*-coding:utf-8-*-
#PartofFlectra.SeeLICENSEfileforfullcopyrightandlicensingdetails.

fromflectra.testsimportForm,tagged,TransactionCase
fromflectra.exceptionsimportMissingError

@tagged('post_install','-at_install')
classTestEmployeeDeletion(TransactionCase):

    deftest_employee_deletion(self):
        #Testsanissuewiththeformviewwheretheemployeecouldbedeleted
        employee_a,employee_b=self.env['hr.employee'].create([
                {
                    'name':'A',
                },
                {
                    'name':'B',
                },
        ])
        department_a,department_b=self.env['hr.department'].create([
            {
                'name':'DEPA',
                'manager_id':employee_a.id,
            },
            {
                'name':'DEPB',
                'manager_id':employee_b.id,
            },
        ])
        employee_a.write({
            'parent_id':employee_a.id,
            'coach_id':employee_a.id,
            'department_id':department_a.id,
        })
        try:
            withForm(employee_a)asform:
                form.department_id=department_b
        exceptMissingError:
            self.fail('Theemployeeshouldnothavebeendeleted')
