#-*-coding:utf-8-*-
#PartofFlectra.SeeLICENSEfileforfullcopyrightandlicensingdetails.

fromflectraimportapi,fields,models,tools


classImLivechatReportChannel(models.Model):
    """LivechatSupportReportontheChannels"""

    _name="im_livechat.report.channel"
    _description="LivechatSupportChannelReport"
    _order='start_date,technical_name'
    _auto=False

    uuid=fields.Char('UUID',readonly=True)
    channel_id=fields.Many2one('mail.channel','Conversation',readonly=True)
    channel_name=fields.Char('ChannelName',readonly=True)
    technical_name=fields.Char('Code',readonly=True)
    livechat_channel_id=fields.Many2one('im_livechat.channel','Channel',readonly=True)
    start_date=fields.Datetime('StartDateofsession',readonly=True,help="Startdateoftheconversation")
    start_hour=fields.Char('StartHourofsession',readonly=True,help="Starthouroftheconversation")
    day_number=fields.Char('DayNumber',readonly=True,help="Daynumberofthesession(1isMonday,7isSunday)")
    time_to_answer=fields.Float('Timetoanswer(sec)',digits=(16,2),readonly=True,group_operator="avg",help="Averagetimeinsecondstogivethefirstanswertothevisitor")
    start_date_hour=fields.Char('HourofstartDateofsession',readonly=True)
    duration=fields.Float('Averageduration',digits=(16,2),readonly=True,group_operator="avg",help="Durationoftheconversation(inseconds)")
    nbr_speaker=fields.Integer('#ofspeakers',readonly=True,group_operator="avg",help="Numberofdifferentspeakers")
    nbr_message=fields.Integer('Averagemessage',readonly=True,group_operator="avg",help="Numberofmessageintheconversation")
    is_without_answer=fields.Integer('Session(s)withoutanswer',readonly=True,group_operator="sum",
                                       help="""Asessioniswithoutansweriftheoperatordidnotanswer.
                                       Ifthevisitorisalsotheoperator,thesessionwillalwaysbeanswered.""")
    days_of_activity=fields.Integer('Daysofactivity',group_operator="max",readonly=True,help="Numberofdayssincethefirstsessionoftheoperator")
    is_anonymous=fields.Integer('Isvisitoranonymous',readonly=True)
    country_id=fields.Many2one('res.country','Countryofthevisitor',readonly=True)
    is_happy=fields.Integer('VisitorisHappy',readonly=True)
    rating=fields.Integer('Rating',group_operator="avg",readonly=True)
    #TODODBE:UseSelectionfield-Need:Piechartmustshowlabels,notkeys.
    rating_text=fields.Char('SatisfactionRate',readonly=True)
    is_unrated=fields.Integer('Sessionnotrated',readonly=True)
    partner_id=fields.Many2one('res.partner','Operator',readonly=True)

    definit(self):
        #Note:start_date_hourmustberemovewhentheread_groupwillallowgroupingonthehourofadatetime.Don'tforgettochangetheview!
        tools.drop_view_if_exists(self.env.cr,'im_livechat_report_channel')
        self.env.cr.execute("""
            CREATEORREPLACEVIEWim_livechat_report_channelAS(
                SELECT
                    C.idasid,
                    C.uuidasuuid,
                    C.idaschannel_id,
                    C.nameaschannel_name,
                    CONCAT(L.name,'/',C.id)astechnical_name,
                    C.livechat_channel_idaslivechat_channel_id,
                    C.create_dateasstart_date,
                    to_char(date_trunc('hour',C.create_date),'YYYY-MM-DDHH24:MI:SS')asstart_date_hour,
                    to_char(date_trunc('hour',C.create_date),'HH24')asstart_hour,
                    extract(dowfrom C.create_date)asday_number,
                    EXTRACT('epoch'FROMMAX(M.create_date)-MIN(M.create_date))ASduration,
                    EXTRACT('epoch'FROMMIN(MO.create_date)-MIN(M.create_date))AStime_to_answer,
                    count(distinctC.livechat_operator_id)asnbr_speaker,
                    count(distinctM.id)asnbr_message,
                    CASE
                        WHENEXISTS(selectdistinctM.author_idFROMmail_messageM,mail_message_mail_channel_relR
                                        WHEREM.author_id=C.livechat_operator_idANDR.mail_channel_id=C.id
                                        ANDR.mail_message_id=M.idandC.livechat_operator_id=M.author_id)
                        THEN0
                        ELSE1
                    ENDasis_without_answer,
                    (DATE_PART('day',date_trunc('day',now())-date_trunc('day',C.create_date))+1)asdays_of_activity,
                    CASE
                        WHENC.anonymous_nameISNULLTHEN0
                        ELSE1
                    ENDasis_anonymous,
                    C.country_id,
                    CASE
                        WHENrate.rating=5THEN1
                        ELSE0
                    ENDasis_happy,
                    Rate.ratingasrating,
                    CASE
                        WHENRate.rating=1THEN'Unhappy'
                        WHENRate.rating=5THEN'Happy'
                        WHENRate.rating=3THEN'Neutral'
                        ELSEnull
                    ENDasrating_text,
                    CASE
                        WHENrate.rating>0THEN0
                        ELSE1
                    ENDasis_unrated,
                    C.livechat_operator_idaspartner_id
                FROMmail_channelC
                    JOINmail_message_mail_channel_relRON(C.id=R.mail_channel_id)
                    JOINmail_messageMON(M.id=R.mail_message_id)
                    JOINim_livechat_channelLON(L.id=C.livechat_channel_id)
                    LEFTJOINmail_messageMOON(R.mail_message_id=MO.idANDMO.author_id=C.livechat_operator_id)
                    LEFTJOINrating_ratingRateON(Rate.res_id=C.idandRate.res_model='mail.channel'andRate.parent_res_model='im_livechat.channel')
                    WHEREC.livechat_operator_idisnotnull
                GROUPBYC.livechat_operator_id,C.id,C.name,C.livechat_channel_id,L.name,C.create_date,C.uuid,Rate.rating
            )
        """)
