#-*-coding:utf-8-*-
#
#py.jsdocumentationbuildconfigurationfile,createdby
#sphinx-quickstartonSunSep 919:36:232012.
#
#Thisfileisexecfile()dwiththecurrentdirectorysettoitscontainingdir.
#
#Notethatnotallpossibleconfigurationvaluesarepresentinthis
#autogeneratedfile.
#
#Allconfigurationvalueshaveadefault;valuesthatarecommentedout
#servetoshowthedefault.

importsys,os

#Ifextensions(ormodulestodocumentwithautodoc)areinanotherdirectory,
#addthesedirectoriestosys.pathhere.Ifthedirectoryisrelativetothe
#documentationroot,useos.path.abspathtomakeitabsolute,likeshownhere.
#sys.path.insert(0,os.path.abspath('.'))

#--Generalconfiguration-----------------------------------------------------

#IfyourdocumentationneedsaminimalSphinxversion,stateithere.
#needs_sphinx='1.0'

#AddanySphinxextensionmodulenameshere,asstrings.Theycanbeextensions
#comingwithSphinx(named'sphinx.ext.*')oryourcustomones.
extensions=['sphinx.ext.todo']

#Addanypathsthatcontaintemplateshere,relativetothisdirectory.
templates_path=['_templates']

#Thesuffixofsourcefilenames.
source_suffix='.rst'

#Theencodingofsourcefiles.
#source_encoding='utf-8-sig'

#Themastertoctreedocument.
master_doc='index'

#Generalinformationabouttheproject.
project=u'py.js'
copyright=u'2012,XavierMorel'

#Theversioninfofortheprojectyou'redocumenting,actsasreplacementfor
#|version|and|release|,alsousedinvariousotherplacesthroughoutthe
#builtdocuments.
#
#TheshortX.Yversion.
version='0.6'
#Thefullversion,includingalpha/beta/rctags.
release='0.6'

#ThelanguageforcontentautogeneratedbySphinx.Refertodocumentation
#foralistofsupportedlanguages.
#language=None

#Therearetwooptionsforreplacing|today|:either,yousettodaytosome
#non-falsevalue,thenitisused:
#today=''
#Else,today_fmtisusedastheformatforastrftimecall.
#today_fmt='%B%d,%Y'

#Listofpatterns,relativetosourcedirectory,thatmatchfilesand
#directoriestoignorewhenlookingforsourcefiles.
exclude_patterns=['_build']

#ThereSTdefaultrole(usedforthismarkup:`text`)touseforalldocuments.
#default_role=None

#Defaultsphinxdomain
default_domain='js'

#Iftrue,'()'willbeappendedto:func:etc.cross-referencetext.
#add_function_parentheses=True

#Iftrue,thecurrentmodulenamewillbeprependedtoalldescription
#unittitles(suchas..function::).
#add_module_names=True

#Iftrue,sectionauthorandmoduleauthordirectiveswillbeshowninthe
#output.Theyareignoredbydefault.
#show_authors=False

#ThenameofthePygments(syntaxhighlighting)styletouse.
pygments_style='sphinx'
#defaultcode-blockhighlighting
highlight_language='javascript'

#Alistofignoredprefixesformoduleindexsorting.
#modindex_common_prefix=[]


#--OptionsforHTMLoutput---------------------------------------------------

#ThethemetouseforHTMLandHTMLHelppages. Seethedocumentationfor
#alistofbuiltinthemes.
html_theme='default'

#Themeoptionsaretheme-specificandcustomizethelookandfeelofatheme
#further. Foralistofoptionsavailableforeachtheme,seethe
#documentation.
#html_theme_options={}

#Addanypathsthatcontaincustomthemeshere,relativetothisdirectory.
#html_theme_path=[]

#ThenameforthissetofSphinxdocuments. IfNone,itdefaultsto
#"<project>v<release>documentation".
#html_title=None

#Ashortertitleforthenavigationbar. Defaultisthesameashtml_title.
#html_short_title=None

#Thenameofanimagefile(relativetothisdirectory)toplaceatthetop
#ofthesidebar.
#html_logo=None

#Thenameofanimagefile(withinthestaticpath)touseasfaviconofthe
#docs. ThisfileshouldbeaWindowsiconfile(.ico)being16x16or32x32
#pixelslarge.
#html_favicon=None

#Addanypathsthatcontaincustomstaticfiles(suchasstylesheets)here,
#relativetothisdirectory.Theyarecopiedafterthebuiltinstaticfiles,
#soafilenamed"default.css"willoverwritethebuiltin"default.css".
html_static_path=['_static']

#Ifnot'',a'Lastupdatedon:'timestampisinsertedateverypagebottom,
#usingthegivenstrftimeformat.
#html_last_updated_fmt='%b%d,%Y'

#Iftrue,SmartyPantswillbeusedtoconvertquotesanddashesto
#typographicallycorrectentities.
#html_use_smartypants=True

#Customsidebartemplates,mapsdocumentnamestotemplatenames.
#html_sidebars={}

#Additionaltemplatesthatshouldberenderedtopages,mapspagenamesto
#templatenames.
#html_additional_pages={}

#Iffalse,nomoduleindexisgenerated.
#html_domain_indices=True

#Iffalse,noindexisgenerated.
#html_use_index=True

#Iftrue,theindexissplitintoindividualpagesforeachletter.
#html_split_index=False

#Iftrue,linkstothereSTsourcesareaddedtothepages.
#html_show_sourcelink=True

#Iftrue,"CreatedusingSphinx"isshownintheHTMLfooter.DefaultisTrue.
#html_show_sphinx=True

#Iftrue,"(C)Copyright..."isshownintheHTMLfooter.DefaultisTrue.
#html_show_copyright=True

#Iftrue,anOpenSearchdescriptionfilewillbeoutput,andallpageswill
#containa<link>tagreferringtoit. Thevalueofthisoptionmustbethe
#baseURLfromwhichthefinishedHTMLisserved.
#html_use_opensearch=''

#ThisisthefilenamesuffixforHTMLfiles(e.g.".xhtml").
#html_file_suffix=None

#OutputfilebasenameforHTMLhelpbuilder.
htmlhelp_basename='pyjsdoc'


#--OptionsforLaTeXoutput--------------------------------------------------

latex_elements={
#Thepapersize('letterpaper'or'a4paper').
#'papersize':'letterpaper',

#Thefontsize('10pt','11pt'or'12pt').
#'pointsize':'10pt',

#AdditionalstufffortheLaTeXpreamble.
#'preamble':'',
}

#GroupingthedocumenttreeintoLaTeXfiles.Listoftuples
#(sourcestartfile,targetname,title,author,documentclass[howto/manual]).
latex_documents=[
  ('index','pyjs.tex',u'py.jsDocumentation',
   u'XavierMorel','manual'),
]

#Thenameofanimagefile(relativetothisdirectory)toplaceatthetopof
#thetitlepage.
#latex_logo=None

#For"manual"documents,ifthisistrue,thentoplevelheadingsareparts,
#notchapters.
#latex_use_parts=False

#Iftrue,showpagereferencesafterinternallinks.
#latex_show_pagerefs=False

#Iftrue,showURLaddressesafterexternallinks.
#latex_show_urls=False

#Documentstoappendasanappendixtoallmanuals.
#latex_appendices=[]

#Iffalse,nomoduleindexisgenerated.
#latex_domain_indices=True


#--Optionsformanualpageoutput--------------------------------------------

#Oneentrypermanualpage.Listoftuples
#(sourcestartfile,name,description,authors,manualsection).
man_pages=[
    ('index','pyjs',u'py.jsDocumentation',
     [u'XavierMorel'],1)
]

#Iftrue,showURLaddressesafterexternallinks.
#man_show_urls=False


#--OptionsforTexinfooutput------------------------------------------------

#GroupingthedocumenttreeintoTexinfofiles.Listoftuples
#(sourcestartfile,targetname,title,author,
# dirmenuentry,description,category)
texinfo_documents=[
  ('index','pyjs',u'py.jsDocumentation',
   u'XavierMorel','pyjs','Onelinedescriptionofproject.',
   'Miscellaneous'),
]

#Documentstoappendasanappendixtoallmanuals.
#texinfo_appendices=[]

#Iffalse,nomoduleindexisgenerated.
#texinfo_domain_indices=True

#HowtodisplayURLaddresses:'footnote','no',or'inline'.
#texinfo_show_urls='footnote'
