#-*-coding:utf-8-*-
#PartofFlectra.SeeLICENSEfileforfullcopyrightandlicensingdetails.

importflectra.tests


@flectra.tests.common.tagged('post_install','-at_install')
classTestUnsplashBeacon(flectra.tests.HttpCase):

    deftest_01_beacon(self):
        self.env['ir.config_parameter'].sudo().set_param('unsplash.app_id','123456')
        #Createpagewithunsplashimage.
        page=self.env['website.page'].search([('url','=','/'),('website_id','=',1)])
        page.arch='''<tname="Homepage"t-name="website.homepage1">
        <tt-call="website.layout">
            <tt-set="pageName"t-value="'homepage'"/>
            <divid="wrap"class="oe_structureoe_empty">
                <imgsrc="/unsplash/pYyOZ8q7AII/306/fairy.jpg"/>
                <!--
                    Keepingthisjavascriptinlineinsteadofextractingit
                    toavoidtemptinguserstopublishsuchafileontheir
                    productionsystem.
                -->
                <script>
                    Object.defineProperty(window,"$",{
                        get(){
                            returnthis._patched$;
                        },
                        set(value){
                            deletethis.$;
                            this._patched$=value;
                            //PatchRPCcall.
                            constoldGet=value.get.bind(this);
                            value.get=(url,data,success,dataType)=>{
                                if(url==="https://views.unsplash.com/v"){
                                    constimageEl=document.querySelector(`img[src^="/unsplash/${data.photo_id}/"]`);
                                    imageEl.dataset.beacon="sent";
                                    return;
                                }
                                returnoldGet(url,data,success,dataType);
                            };
                        },
                    });
                </script>
            </div>
            </t>
        </t>'''
        #Accesspage.
        self.start_tour('/','test_unsplash_beacon')
